export { DomainValidationError } from './errors.js';
export { createAnalysisJob, transitionAnalysisJob } from './job.js';
export type {
  AnalysisJob,
  AnalysisJobStatus,
  CreateAnalysisJobInput,
  TransitionAnalysisJobInput,
} from './job.js';
export {
  createAnalysisResult,
  createDimensionScore,
  createEvidence,
  createFact,
  createFinding,
  createMetric,
  createProvenance,
  createRecommendation,
  createRepositorySnapshot,
} from './factories.js';
export type {
  AnalysisDimension,
  AnalysisResult,
  AnalysisSource,
  ConfidenceBand,
  Coverage,
  DimensionScore,
  Evidence,
  EvidenceKind,
  EvidenceLocation,
  Fact,
  FactType,
  FactValue,
  Finding,
  Metadata,
  MetadataValue,
  Metric,
  ObservationStatus,
  Provenance,
  Recommendation,
  RecommendationPriority,
  RepositorySnapshot,
  Severity,
  SourcePosition,
  SourceRange,
} from './types.js';
export type {
  CreateAnalysisResultInput,
  CreateDimensionScoreInput,
  CreateEvidenceInput,
  CreateFactInput,
  CreateFindingInput,
  CreateMetricInput,
  CreateProvenanceInput,
  CreateRecommendationInput,
  CreateRepositorySnapshotInput,
} from './factories.js';
